### ISSUE TITLE
Observer was not Registered

### ISSUE THREAD

**Issue by nicksurya** [thesurix/gesture-recycler#2]
Thanks for the lib,

btw, i have a problem, it's happened when i press back, and the activity destroyed then 

``````
    Caused by: java.lang.IllegalStateException: Observer com.thesurix.gesturerecycler.EmptyViewDataObserver@1e8b038a was not registered.
       at android.database.Observable.unregisterObserver(Observable.java:69)
       at android.support.v7.widget.RecyclerView$Adapter.unregisterAdapterDataObserver(RecyclerView.java:5676)
       at com.thesurix.gesturerecycler.GestureAdapter$1.onViewDetachedFromWindow(GestureAdapter.java:82)
       at android.view.View.dispatchDetachedFromWindow(View.java:13633)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2966)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2963)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2963)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2963)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4296)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4269)
       at android.view.ViewGroup.removeView(ViewGroup.java:4201)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1165)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
       at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2083)
       at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:244)
       at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:369)
       at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:199)
       at android.app.Activity.performDestroy(Activity.java:6156)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1147)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3866)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3897) 
       at android.app.ActivityThread.access$1400(ActivityThread.java:167) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
       at android.os.Handler.dispatchMessage(Handler.java:111) 
       at android.os.Looper.loop(Looper.java:194) 
       at android.app.ActivityThread.main(ActivityThread.java:5546) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:372) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) ```
``````

**Comment by thesurix** [comment]
Hi
Could you give steps to reproduce or sample code?

**Comment by emreaktrk** [comment]
I have same problem. Nothing spesicial.

`package com.akturk.momentify.ui.create.video;

import android.net.Uri;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.Toast;

import com.akturk.momentify.R;
import com.akturk.momentify.component.pipeline.Step;
import com.akturk.momentify.event.OnVideoStepOneCompleteEvent;
import com.akturk.momentify.model.Video;
import com.bumptech.glide.Glide;
import com.squareup.otto.Subscribe;
import com.thesurix.gesturerecycler.GestureAdapter;
import com.thesurix.gesturerecycler.GestureManager;
import com.thesurix.gesturerecycler.GestureViewHolder;

import java.io.File;
import java.util.ArrayList;

public final class VideoStepTwo extends Step implements View.OnClickListener {

```
private RecyclerView mRecyclerView;
private Button mButton;
private ArrayList<Video> mList;


@Override
protected int getLayoutResource() {
    return R.layout.step_video_two;
}

@Override
protected void onViewInflated(View view) {
    super.onViewInflated(view);

    mRecyclerView = (RecyclerView) view.findViewById(R.id.video_step_two_recycler);
    mButton = (Button) view.findViewById(R.id.video_step_two_button);
}

@Override
public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
    super.onViewCreated(view, savedInstanceState);

    mButton.setOnClickListener(this);
}

@Override
public void onClick(View view) {
    Toast.makeText(getContext(), "Merging will be implemented.", Toast.LENGTH_SHORT).show();
}

@Subscribe
public void onVideoStepOneCompleteEvent(OnVideoStepOneCompleteEvent event) {
    mList = event.mVideos;

    VideoAdapter adapter = new VideoAdapter();
    LinearLayoutManager linearLayoutManager = new LinearLayoutManager(getContext());

    mRecyclerView.setHasFixedSize(true);
    mRecyclerView.setLayoutManager(linearLayoutManager);
    mRecyclerView.setAdapter(adapter);

    new GestureManager
            .Builder(mRecyclerView)
            .setSwipeEnabled(false)
            .setLongPressDragEnabled(true)
            .build();
}


private class VideoHolder extends GestureViewHolder {

    private ImageView mImageView;

    public VideoHolder(View itemView) {
        super(itemView);

        mImageView = (ImageView) itemView.findViewById(R.id.cell_video_order_imageview);
    }

    @Override
    public boolean canDrag() {
        return true;
    }

    @Override
    public boolean canSwipe() {
        return false;
    }
}


private class VideoAdapter extends GestureAdapter<Video, VideoHolder> {


    @Override
    public VideoHolder onCreateViewHolder(final ViewGroup parent, final int viewType) {
        View view = LayoutInflater.from(getContext()).inflate(R.layout.cell_video_order, parent, false);
        return new VideoHolder(view);
    }

    @Override
    public void onBindViewHolder(final VideoHolder holder, final int position) {
        super.onBindViewHolder(holder, position);
        Video video = mList.get(position);

        File file = new File(video.getThumbnail());
        Uri uri = Uri.fromFile(file);

        Glide
                .with(getContext())
                .load(uri)
                .centerCrop()
                .into(holder.mImageView);

    }

    @Override
    public int getItemCount() {
        return mList.size();
    }
}
```

}
`

**Comment by emreaktrk** [comment]
btw, i figured out i should use setData method, otherwise i am having index out of bound exception :)

**Comment by emreaktrk** [comment]
I think you may need to run your unregister methods in UI thread.

**Comment by thesurix** [comment]
@emreaktrk 
Yes, you should use `setData()`. You can use own implementation only when swipe & drag is disabled.
I think there should be some observer validation to prevent `java.lang.IllegalStateException`.

**Comment by emreaktrk** [comment]
as i remember the code base, its trying to attach observer in onAttach method. But why the error says not registered? Maybe observer coming null? We should investigate the problem. My forecast is, this problem occurs when using a fragment. (I might be wrong :) its just an idea.)

**Comment by thesurix** [comment]
This issue occurs in `onViewDetachedFromWindow()` so I think `onViewAttachedToWindow()` was not called. By the way all examples use fragments and I never get this exception :) maybe something with the fragment lifecycle?

**Comment by emreaktrk** [comment]
It could be, i researched stackoverflow and suggestions are calling register observer method in UI thread. As i know some of lifecycle methods are called from another thread like onCreate and onDestroy. Similar architecture could be in fragments too. :/

**Comment by emreaktrk** [comment]
Did you find a solution?

**Comment by thesurix** [comment]
Fixed in [commit e97af0](https://github.com/thesurix/gesture-recycler/commit/e97af0e700434f95b50d157195327a26710007b8). If you still have problems, please let me know.
